from pathlib import Path
import shutil

from docx import Document


SOURCE = Path(r"D:\AI\NCKH\Script_bao_cao.docx")
OUTPUT_DIR = Path(__file__).resolve().parents[2] / "deliverables"
OUTPUT = OUTPUT_DIR / "Script_bao_cao_DA_CHINH_SUA_lesion_level.docx"


REVISED_PARAGRAPHS = {
    1: """[CÃ¢u má»Ÿ Ä‘áº§u - Hook]: KÃ­nh thÆ°a quÃ½ tháº§y cÃ´ trong há»™i Ä‘á»“ng, cÃ¹ng toÃ n thá»ƒ cÃ¡c báº¡n sinh viÃªn Ä‘ang cÃ³ máº·t trong buá»•i bÃ¡o cÃ¡o ngÃ y hÃ´m nay. ÄÃ£ bao giá» chÃºng ta tá»± há»i: Khi má»™t bÃ¡c sÄ© da liá»…u nhÃ¬n vÃ o má»™t ná»‘t ruá»“i trÃªn da bá»‡nh nhÃ¢n, liá»‡u há» chá»‰ nhÃ¬n vÃ o mÃ u sáº¯c, hÃ¬nh dÃ¡ng cá»§a ná»‘t ruá»“i Ä‘Ã³, hay há» cÃ²n xÃ©t Ä‘áº¿n Ä‘á»™ tuá»•i, giá»›i tÃ­nh vÃ  vá»‹ trÃ­ cá»§a nÃ³ trÃªn cÆ¡ thá»ƒ? [Ná»™i dung chÃ­nh]: CÃ¢u tráº£ lá»i cháº¯c cháº¯n lÃ  cÃ³. Cháº©n Ä‘oÃ¡n y khoa luÃ´n lÃ  má»™t quÃ¡ trÃ¬nh tá»•ng hÃ²a cá»§a nhiá»u luá»“ng thÃ´ng tin. Tuy nhiÃªn, pháº§n lá»›n cÃ¡c mÃ´ hÃ¬nh TrÃ­ tuá»‡ NhÃ¢n táº¡o hiá»‡n nay láº¡i Ä‘ang bá» quÃªn Ä‘iá»u Ä‘Ã³. HÃ´m nay, Ä‘áº¡i diá»‡n cho nhÃ³m nghiÃªn cá»©u Ä‘áº¿n tá»« MIND Lab, em xin trÃ¬nh bÃ y Ä‘á» tÃ i: "Multimodal Deep Learning with Clinical Metadata for Enhanced Skin Cancer Diagnosis" - á»¨ng dá»¥ng há»c sÃ¢u Ä‘a phÆ°Æ¡ng thá»©c káº¿t há»£p siÃªu dá»¯ liá»‡u lÃ¢m sÃ ng nháº±m nÃ¢ng cao hiá»‡u quáº£ cháº©n Ä‘oÃ¡n ung thÆ° da. DÆ°á»›i sá»± hÆ°á»›ng dáº«n cá»§a TS. LÃª Thá»‹ Thu Nga, nhÃ³m chÃºng em hÆ°á»›ng tá»›i viá»‡c xÃ¢y dá»±ng má»™t mÃ´ hÃ¬nh AI há»— trá»£ Ä‘Ã¡nh giÃ¡ nguy cÆ¡ Ã¡c tÃ­nh báº±ng cÃ¡ch káº¿t há»£p hÃ¬nh áº£nh vá»›i bá»‘i cáº£nh lÃ¢m sÃ ng. [CÃ¢u káº¿t/Chuyá»ƒn Ã½]: Váº­y táº¡i sao viá»‡c chá»‰ sá»­ dá»¥ng hÃ¬nh áº£nh láº¡i lÃ  khÃ´ng Ä‘á»§ trong cháº©n Ä‘oÃ¡n ung thÆ° da? KÃ­nh má»i há»™i Ä‘á»“ng cÃ¹ng nhÃ¬n vÃ o thá»±c táº¿ lÃ¢m sÃ ng á»Ÿ slide tiáº¿p theo.""",
    3: """[CÃ¢u tiáº¿p ná»‘i]: KÃ­nh thÆ°a há»™i Ä‘á»“ng, ung thÆ° da, Ä‘áº·c biá»‡t lÃ  ung thÆ° háº¯c tá»‘ (melanoma), lÃ  má»™t bá»‡nh lÃ½ mÃ  viá»‡c phÃ¡t hiá»‡n sá»›m cÃ³ Ã½ nghÄ©a ráº¥t quan trá»ng. [Ná»™i dung chÃ­nh]: Äá»ƒ há»— trá»£ Ä‘iá»u nÃ y, ká»¹ thuáº­t ná»™i soi da (Dermoscopy) ra Ä‘á»i, giÃºp quan sÃ¡t rÃµ hÆ¡n cÃ¡c cáº¥u trÃºc vi mÃ´. Tuy nhiÃªn, gÃ³c nhÃ¬n thá»‹ giÃ¡c nÃ y váº«n tá»“n táº¡i nhá»¯ng giá»›i háº¡n Ä‘Ã¡ng lÆ°u Ã½. Thá»© nháº¥t, trong thá»±c táº¿ lÃ¢m sÃ ng, má»™t tá»•n thÆ°Æ¡ng lÃ nh tÃ­nh vÃ  má»™t tá»•n thÆ°Æ¡ng Ã¡c tÃ­nh á»Ÿ giai Ä‘oáº¡n Ä‘áº§u cÃ³ thá»ƒ cÃ³ hÃ¬nh thÃ¡i quang há»c ráº¥t giá»‘ng nhau. ThÃªm vÃ o Ä‘Ã³, áº£nh chá»¥p thÆ°á»ng bá»‹ nhiá»…u bá»Ÿi cÃ¡c yáº¿u tá»‘ váº­t lÃ½ nhÆ° sá»£i lÃ´ng, bá»t khÃ­ gel hay Ä‘iá»u kiá»‡n chiáº¿u sÃ¡ng. Nhá»¯ng nhiá»…u nÃ y cÃ³ thá»ƒ áº£nh hÆ°á»Ÿng Ä‘áº¿n cáº£ Ä‘Ã¡nh giÃ¡ cá»§a con ngÆ°á»i láº«n máº¡ng nÆ¡-ron nhÃ¢n táº¡o. Thá»© hai, báº£n thÃ¢n phÆ°Æ¡ng phÃ¡p ná»™i soi váº«n phá»¥ thuá»™c Ä‘Ã¡ng ká»ƒ vÃ o kinh nghiá»‡m vÃ  nháº­n Ä‘á»‹nh cá»§a ngÆ°á»i khÃ¡m. [CÃ¢u káº¿t/Chuyá»ƒn Ã½]: ChÃ­nh vÃ¬ thá»‹ giÃ¡c cÃ³ nhá»¯ng "Ä‘iá»ƒm mÃ¹" nháº¥t Ä‘á»‹nh, cÃ¡c nghiÃªn cá»©u AI cáº§n quan tÃ¢m khÃ´ng chá»‰ Ä‘áº¿n kiáº¿n trÃºc mÃ´ hÃ¬nh, mÃ  cÃ²n Ä‘áº¿n tÃ­nh cháº·t cháº½ cá»§a giao thá»©c Ä‘Ã¡nh giÃ¡. ÄÃ³ lÃ  ná»™i dung cá»§a slide tiáº¿p theo.""",
    5: """[CÃ¢u tiáº¿p ná»‘i]: Khi kháº£o sÃ¡t cÃ¡c nghiÃªn cá»©u State-of-the-Art (SOTA) hiá»‡n nay, chÃºng em nháº­n tháº¥y nhiá»u cÃ´ng trÃ¬nh bÃ¡o cÃ¡o hiá»‡u nÄƒng ráº¥t cao, vá»›i AUC cÃ³ thá»ƒ lÃªn tá»›i trÃªn 95%. Tuy nhiÃªn, Ä‘áº±ng sau nhá»¯ng con sá»‘ Ä‘Ã³ lÃ  hai váº¥n Ä‘á» phÆ°Æ¡ng phÃ¡p luáº­n cáº§n Ä‘Æ°á»£c kiá»ƒm soÃ¡t. [Ná»™i dung chÃ­nh]: Váº¥n Ä‘á» Ä‘áº§u tiÃªn lÃ  RÃ² rá»‰ dá»¯ liá»‡u á»Ÿ cáº¥p Ä‘á»™ tá»•n thÆ°Æ¡ng (Lesion-level Data Leakage). Náº¿u dá»¯ liá»‡u Ä‘Æ°á»£c chia ngáº«u nhiÃªn theo tá»«ng áº£nh, nhiá»u áº£nh thuá»™c cÃ¹ng má»™t tá»•n thÆ°Æ¡ng cÃ³ thá»ƒ xuáº¥t hiá»‡n á»Ÿ cáº£ táº­p huáº¥n luyá»‡n vÃ  táº­p Ä‘Ã¡nh giÃ¡. Khi Ä‘Ã³, mÃ´ hÃ¬nh cÃ³ nguy cÆ¡ ghi nhá»› Ä‘áº·c Ä‘iá»ƒm riÃªng cá»§a tá»•n thÆ°Æ¡ng hoáº·c Ä‘iá»u kiá»‡n thu nháº­n áº£nh, thay vÃ¬ há»c quy luáº­t tá»•ng quÃ¡t cá»§a bá»‡nh lÃ½. Váº¥n Ä‘á» thá»© hai lÃ  Sá»± láº¥n Ã¡t phÆ°Æ¡ng thá»©c (Modality Dominance). Khi káº¿t há»£p hÃ¬nh áº£nh vá»›i dá»¯ liá»‡u lÃ¢m sÃ ng nhÆ° tuá»•i, giá»›i tÃ­nh vÃ  vá»‹ trÃ­ báº±ng phÃ©p ná»‘i ghÃ©p Ä‘Æ¡n giáº£n (Concatenation), vector hÃ¬nh áº£nh cÃ³ thá»ƒ chiáº¿m Æ°u tháº¿ so vá»›i tÃ­n hiá»‡u lÃ¢m sÃ ng cÃ³ sá»‘ chiá»u nhá» hÆ¡n. [CÃ¢u káº¿t/Chuyá»ƒn Ã½]: Tá»« hai váº¥n Ä‘á» nÃ y, nhÃ³m nghiÃªn cá»©u cá»§a chÃºng em xÃ¢y dá»±ng má»™t khung Ä‘Ã¡nh giÃ¡ cháº·t cháº½ hÆ¡n, Ä‘á»“ng thá»i kháº£o sÃ¡t cÆ¡ cháº¿ dung há»£p giÃºp metadata tham gia hiá»‡u quáº£ hÆ¡n vÃ o quyáº¿t Ä‘á»‹nh cá»§a mÃ´ hÃ¬nh.""",
    7: """[CÃ¢u tiáº¿p ná»‘i]: Äá»ƒ giáº£i quyáº¿t váº¥n Ä‘á», chÃºng em Ä‘á» ra 4 má»¥c tiÃªu cá»‘t lÃµi, xoay quanh triáº¿t lÃ½: "AI pháº£i an toÃ n, minh báº¡ch vÃ  há»— trá»£ Ä‘Æ°á»£c quÃ¡ trÃ¬nh Ä‘Ã¡nh giÃ¡ lÃ¢m sÃ ng". [Ná»™i dung chÃ­nh]: Thá»© nháº¥t, Háº¡n cháº¿ Data Leakage. NhÃ³m thiáº¿t láº­p giao thá»©c phÃ¢n tÃ¡ch dá»¯ liá»‡u theo ID tá»•n thÆ°Æ¡ng, nháº±m báº£o Ä‘áº£m cÃ¡c áº£nh thuá»™c cÃ¹ng má»™t tá»•n thÆ°Æ¡ng khÃ´ng Ä‘á»“ng thá»i xuáº¥t hiá»‡n á»Ÿ táº­p há»c vÃ  táº­p Ä‘Ã¡nh giÃ¡. Thá»© hai, xÃ¢y dá»±ng Khung Ä‘a phÆ°Æ¡ng thá»©c (Multimodal Framework), káº¿t há»£p áº£nh ná»™i soi vá»›i metadata trÆ°á»›c cháº©n Ä‘oÃ¡n Ä‘á»ƒ cung cáº¥p thÃªm bá»‘i cáº£nh cho mÃ´ hÃ¬nh. Thá»© ba, Tá»‘i Æ°u hÃ³a dung há»£p. Thay vÃ¬ chá»‰ ná»‘i ghÃ©p thá»¥ Ä‘á»™ng, chÃºng em triá»ƒn khai vÃ  so sÃ¡nh cÃ¡c chiáº¿n lÆ°á»£c dung há»£p, trong Ä‘Ã³ FiLM lÃ  cÆ¡ cháº¿ trá»ng tÃ¢m Ä‘á»ƒ metadata Ä‘iá»u biáº¿n trá»±c tiáº¿p Ä‘áº·c trÆ°ng áº£nh. VÃ  cuá»‘i cÃ¹ng, Minh báº¡ch quyáº¿t Ä‘á»‹nh. NhÃ³m sá»­ dá»¥ng cÃ¡c cÃ´ng cá»¥ Explainable AI (XAI) Ä‘á»ƒ kháº£o sÃ¡t vÃ¹ng áº£nh mÃ´ hÃ¬nh chÃº Ã½ vÃ  má»©c Ä‘Ã³ng gÃ³p cá»§a cÃ¡c biáº¿n lÃ¢m sÃ ng. [CÃ¢u káº¿t/Chuyá»ƒn Ã½]: Äá»ƒ hiá»‡n thá»±c hÃ³a cÃ¡c má»¥c tiÃªu nÃ y, bÃ i toÃ¡n Ä‘áº§u tiÃªn chÃºng em pháº£i Ä‘á»‘i máº·t chÃ­nh lÃ  sá»± phá»©c táº¡p cá»§a táº­p dá»¯ liá»‡u y khoa.""",
    9: """[CÃ¢u tiáº¿p ná»‘i]: KÃ­nh thÆ°a há»™i Ä‘á»“ng, má»™t mÃ´ hÃ¬nh tá»‘t khÃ´ng thá»ƒ Ä‘Æ°á»£c kiá»ƒm chá»©ng náº¿u chá»‰ cháº¡y trÃªn má»™t táº­p dá»¯ liá»‡u "sáº¡ch sáº½" vÃ  nhÃ¢n táº¡o. Do Ä‘Ã³, chÃºng em chá»n Ä‘Ã¡nh giÃ¡ trÃªn hai bá»™ dá»¯ liá»‡u lá»›n vá»›i hai Ä‘áº·c Ä‘iá»ƒm khÃ¡c nhau. [Ná»™i dung chÃ­nh]: Bá»™ Ä‘áº§u tiÃªn lÃ  HAM10000 vá»›i 10.015 áº£nh. Äiá»ƒm Ä‘áº·c thÃ¹ cá»§a bá»™ nÃ y lÃ  sá»± máº¥t cÃ¢n báº±ng máº¡nh, khi lá»›p tá»•n thÆ°Æ¡ng lÃ nh tÃ­nh nhÆ° Nevus chiáº¿m tá»· lá»‡ lá»›n. ÄÃ¢y lÃ  thÃ¡ch thá»©c Ä‘á»‘i vá»›i kháº£ nÄƒng nháº­n diá»‡n cÃ¡c ca Ã¡c tÃ­nh Ã­t gáº·p hÆ¡n. Bá»™ thá»© hai lÃ  BCN20000 vá»›i quy mÃ´ xáº¥p xá»‰ 19 nghÃ¬n áº£nh theo mÃ´ táº£ cá»§a bá»™ dá»¯ liá»‡u, cÃ³ tÃ­nh Ä‘a dáº¡ng cao hÆ¡n vá» Ä‘iá»u kiá»‡n thu nháº­n vÃ  loáº¡i tá»•n thÆ°Æ¡ng. Vá»›i cáº£ hai bá»™ dá»¯ liá»‡u, Ä‘áº§u vÃ o Ä‘a phÆ°Æ¡ng thá»©c cá»§a chÃºng em bao gá»“m áº¢nh Dermoscopy káº¿t há»£p vá»›i siÃªu dá»¯ liá»‡u trÆ°á»›c cháº©n Ä‘oÃ¡n nhÆ° Tuá»•i, Giá»›i tÃ­nh vÃ  Vá»‹ trÃ­ giáº£i pháº«u. Trong thiáº¿t láº­p thá»±c nghiá»‡m cá»§a nghiÃªn cá»©u, Ä‘áº§u ra Ä‘Æ°á»£c Ä‘Ã¡nh giÃ¡ theo bÃ i toÃ¡n nhá»‹ phÃ¢n: LÃ nh tÃ­nh vÃ  Ãc tÃ­nh. [CÃ¢u káº¿t/Chuyá»ƒn Ã½]: Sá»± phá»©c táº¡p cá»§a dá»¯ liá»‡u thÃ´ Ä‘Ã²i há»i má»™t giao thá»©c tiá»n xá»­ lÃ½ vÃ  thanh lá»c cáº©n trá»ng trÆ°á»›c khi Ä‘Æ°a vÃ o máº¡ng nÆ¡-ron.""",
    11: """[CÃ¢u tiáº¿p ná»‘i]: á»ž bÆ°á»›c nÃ y, chÃºng em thiáº¿t láº­p má»™t "bá»™ lá»c" nghiÃªm ngáº·t mang tÃªn Giao Thá»©c ToÃ n Váº¹n, chia lÃ m hai máº·t tráº­n: Xá»­ lÃ½ hÃ¬nh áº£nh vÃ  Thanh lá»c biáº¿n sá»‘. [Ná»™i dung chÃ­nh]: Vá» máº·t hÃ¬nh áº£nh, nhÆ° há»™i Ä‘á»“ng cÃ³ thá»ƒ tháº¥y trÃªn slide (chá»‰ tay vÃ o áº£nh Before/After), chÃºng em Ã¡p dá»¥ng thuáº­t toÃ¡n lá»c hÃ¬nh thÃ¡i há»c káº¿t há»£p DullRazor Ä‘á»ƒ giáº£m áº£nh hÆ°á»Ÿng cá»§a cÃ¡c cáº¥u trÃºc lÃ´ng che khuáº¥t tá»•n thÆ°Æ¡ng. Sau Ä‘Ã³, cÃ¡c bÆ°á»›c chuáº©n hÃ³a mÃ u vÃ  tÄƒng cÆ°á»ng tÆ°Æ¡ng pháº£n há»— trá»£ lÃ m rÃµ cáº¥u trÃºc cáº§n quan sÃ¡t trÃªn áº£nh. Vá» máº·t siÃªu dá»¯ liá»‡u, nhÃ³m chá»‰ sá»­ dá»¥ng cÃ¡c thÃ´ng tin cÃ³ Ã½ nghÄ©a trÆ°á»›c cháº©n Ä‘oÃ¡n nhÆ° tuá»•i, giá»›i tÃ­nh vÃ  vá»‹ trÃ­ giáº£i pháº«u; cÃ¡c biáº¿n cÃ³ thá»ƒ tiáº¿t lá»™ káº¿t quáº£ cháº©n Ä‘oÃ¡n khÃ´ng Ä‘Æ°á»£c Ä‘Æ°a vÃ o Ä‘áº§u vÃ o mÃ´ hÃ¬nh. Trá»ng tÃ¢m cá»§a giao thá»©c Ä‘Ã¡nh giÃ¡ lÃ  Lesion-level Split: chÃºng em gom nhÃ³m cÃ¡c máº«u theo `lesion_id`, báº£o Ä‘áº£m cÃ¡c áº£nh cá»§a cÃ¹ng má»™t tá»•n thÆ°Æ¡ng khÃ´ng bá»‹ phÃ¢n tÃ¡ch sang cáº£ táº­p huáº¥n luyá»‡n vÃ  táº­p Ä‘Ã¡nh giÃ¡. [CÃ¢u káº¿t/Chuyá»ƒn Ã½]: Sau khi Ä‘Ã£ cÃ³ dá»¯ liá»‡u vÃ  quy trÃ¬nh chia tÃ¡ch phÃ¹ há»£p, cá»‘t lÃµi cá»§a nghiÃªn cá»©u náº±m á»Ÿ viá»‡c: LÃ m sao Ä‘á»ƒ káº¿t há»£p HÃ¬nh áº£nh vÃ  Metadata má»™t cÃ¡ch hiá»‡u quáº£ nháº¥t?""",
    21: """BÆ°á»›c 4: Vector Ä‘áº·c trÆ°ng cuá»‘i cÃ¹ng sáº½ Ä‘i qua Head Classification Ä‘á»ƒ Ä‘Æ°a ra phÃ¢n loáº¡i LÃ nh tÃ­nh hay Ãc tÃ­nh. Äáº·c biá»‡t, káº¿t quáº£ nÃ y khÃ´ng chá»‰ dá»«ng láº¡i á»Ÿ con sá»‘, mÃ  cÃ²n Ä‘Æ°á»£c phÃ¢n tÃ­ch thÃªm báº±ng module XAI (Grad-CAM vÃ  SHAP) nháº±m kháº£o sÃ¡t quÃ¡ trÃ¬nh ra quyáº¿t Ä‘á»‹nh. [CÃ¢u káº¿t/Chuyá»ƒn Ã½]: Trong sá»‘ 4 cÆ¡ cháº¿ táº¡i BÆ°á»›c 3, FiLM lÃ  phÆ°Æ¡ng phÃ¡p trá»ng tÃ¢m mÃ  nhÃ³m muá»‘n Ä‘Ã¡nh giÃ¡. Váº­y FiLM thá»±c sá»± hoáº¡t Ä‘á»™ng báº±ng toÃ¡n há»c nhÆ° tháº¿ nÃ o?""",
    23: """[CÃ¢u tiáº¿p ná»‘i]: ThÆ°a há»™i Ä‘á»“ng, Ä‘Ã¢y lÃ  phÆ°Æ¡ng trÃ¬nh biá»ƒu diá»…n cÆ¡ cháº¿ FiLM (Feature-wise Linear Modulation) mÃ  nhÃ³m sá»­ dá»¥ng. [Ná»™i dung chÃ­nh]: Ã tÆ°á»Ÿng cá»‘t lÃµi cá»§a FiLM lÃ : thay vÃ¬ chá»‰ ná»‘i metadata vÃ o cuá»‘i máº¡ng, FiLM cho phÃ©p thÃ´ng tin lÃ¢m sÃ ng tÃ¡c Ä‘á»™ng trá»±c tiáº¿p lÃªn biá»ƒu diá»…n thá»‹ giÃ¡c. Cá»¥ thá»ƒ, Vector Metadata sáº½ Ä‘i qua má»™t Generator Ä‘á»ƒ sinh ra hai tham sá»‘: Gamma (Scale) vÃ  Beta (Shift). Trong Ä‘Ã³, Gamma Ä‘Ã³ng vai trÃ² phÃ³ng to hoáº·c thu nhá» má»©c kÃ­ch hoáº¡t cá»§a cÃ¡c Ä‘áº·c trÆ°ng áº£nh, cÃ²n Beta giÃºp dá»‹ch chuyá»ƒn biá»ƒu diá»…n Ä‘Ã³. VÃ­ dá»¥, vá»›i bá»‡nh nhÃ¢n lá»›n tuá»•i cÃ³ tá»•n thÆ°Æ¡ng táº¡i vÃ¹ng phÆ¡i náº¯ng nhiá»u, metadata cÃ³ thá»ƒ lÃ m thay Ä‘á»•i cÃ¡ch mÃ´ hÃ¬nh cÃ¢n nháº¯c cÃ¡c Ä‘áº·c trÆ°ng hÃ¬nh áº£nh liÃªn quan. NhÆ° váº­y, FiLM táº¡o cÆ¡ cháº¿ Ä‘á»ƒ metadata tham gia trá»±c tiáº¿p hÆ¡n vÃ o quyáº¿t Ä‘á»‹nh, thay vÃ¬ bá»‹ phá»¥ thuá»™c hoÃ n toÃ n vÃ o phÃ©p ná»‘i ghÃ©p cuá»‘i máº¡ng. [CÃ¢u káº¿t/Chuyá»ƒn Ã½]: Äá»ƒ Ä‘Ã¡nh giÃ¡ cÆ¡ cháº¿ nÃ y trong thá»±c táº¿, chÃºng em thiáº¿t káº¿ má»™t chiáº¿n thuáº­t huáº¥n luyá»‡n vÃ  kiá»ƒm Ä‘á»‹nh cháº·t cháº½.""",
    25: """[CÃ¢u tiáº¿p ná»‘i]: Viá»‡c huáº¥n luyá»‡n má»™t máº¡ng nÆ¡-ron Ä‘a phÆ°Æ¡ng thá»©c trÃªn dá»¯ liá»‡u máº¥t cÃ¢n báº±ng Ä‘Ã²i há»i má»™t chiáº¿n thuáº­t tá»‘i Æ°u hÃ³a chuyÃªn biá»‡t. [Ná»™i dung chÃ­nh]: Äáº§u tiÃªn, quy trÃ¬nh Ä‘Ã¡nh giÃ¡ lÃ  5-Fold Stratified Group Cross-Validation. NghÄ©a lÃ  dá»¯ liá»‡u Ä‘Æ°á»£c chia lÃ m 5 náº¿p gáº¥p, cá»‘ gáº¯ng duy trÃ¬ phÃ¢n bá»‘ nhÃ£n vÃ  cÃ¡ch ly cÃ¡c áº£nh thuá»™c cÃ¹ng má»™t `lesion_id` giá»¯a Train vÃ  Validation. Trong bÃ i bÃ¡o, chÃºng em kháº£o sÃ¡t nhiá»u kiáº¿n trÃºc nhÆ° ConvNeXt, ResNet50, EfficientNet-B4 vÃ  Vision Transformer nháº±m Ä‘Ã¡nh giÃ¡ áº£nh hÆ°á»Ÿng cá»§a cÆ¡ cháº¿ dung há»£p trÃªn cÃ¡c backbone khÃ¡c nhau. Äá»ƒ xá»­ lÃ½ máº¥t cÃ¢n báº±ng lá»›p, Ä‘áº·c biá»‡t á»Ÿ HAM10000, nhÃ³m sá»­ dá»¥ng Focal BCE Loss vá»›i gamma báº±ng 2 vÃ  alpha báº±ng 0,75, giÃºp mÃ´ hÃ¬nh táº­p trung hÆ¡n vÃ o cÃ¡c máº«u khÃ³. QuÃ¡ trÃ¬nh há»c Ä‘Æ°á»£c duy trÃ¬ á»•n Ä‘á»‹nh báº±ng thuáº­t toÃ¡n tá»‘i Æ°u AdamW káº¿t há»£p vá»›i lá»‹ch trÃ¬nh há»c Cosine Annealing. [CÃ¢u káº¿t/Chuyá»ƒn Ã½]: Vá»›i thiáº¿t láº­p nÃ y, nhÃ³m xin phÃ©p trÃ¬nh bÃ y káº¿t quáº£ thá»±c nghiá»‡m Ä‘áº¡t Ä‘Æ°á»£c á»Ÿ slide tiáº¿p theo.""",
    27: """[CÃ¢u tiáº¿p ná»‘i]: KÃ­nh thÆ°a há»™i Ä‘á»“ng, trÃªn mÃ n hÃ¬nh lÃ  káº¿t quáº£ trung bÃ¬nh sau 5-Fold Cross Validation Ä‘Æ°á»£c bÃ¡o cÃ¡o trong bÃ i bÃ¡o. ÄÃ¢y lÃ  káº¿t quáº£ tá»•ng há»£p qua cÃ¡c fold thay vÃ¬ chá»‰ dá»±a trÃªn má»™t láº§n chia dá»¯ liá»‡u. [Ná»™i dung chÃ­nh]: NhÃ¬n vÃ o báº£ng, cÆ¡ cháº¿ FiLM (Strategy 3) cho tháº¥y hiá»‡u quáº£ phá»¥ thuá»™c vÃ o tá»«ng backbone. Ná»•i báº­t nháº¥t lÃ  cáº¥u hÃ¬nh ConvNeXt + FiLM trÃªn HAM10000, Ä‘áº¡t AUC trung bÃ¬nh 94,02% vá»›i Ä‘á»™ lá»‡ch chuáº©n +/-0,11, cao hÆ¡n cáº¥u hÃ¬nh Image-Only tÆ°Æ¡ng á»©ng lÃ  92,56% +/-0,78. Vá»›i ViT trÃªn HAM10000, FiLM cÅ©ng Ä‘áº¡t AUC 87,35% +/-0,28. BÃªn cáº¡nh Ä‘Ã³, EfficientNet-B4 + FiLM trÃªn HAM10000 Ä‘áº¡t Specificity 94,26% +/-2,41. Äá»™ Ä‘áº·c hiá»‡u cao cho tháº¥y mÃ´ hÃ¬nh cÃ³ tiá»m nÄƒng giáº£m tá»· lá»‡ dÆ°Æ¡ng tÃ­nh giáº£ táº¡i ngÆ°á»¡ng Ä‘Ã¡nh giÃ¡ Ä‘Æ°á»£c sá»­ dá»¥ng, dÃ¹ Ä‘á»ƒ kháº³ng Ä‘á»‹nh tÃ¡c Ä‘á»™ng trong thá»±c táº¿ lÃ¢m sÃ ng váº«n cáº§n thÃªm Ä‘Ã¡nh giÃ¡ chuyÃªn mÃ´n. TrÃªn BCN20000, ViT káº¿t há»£p FiLM Ä‘áº¡t AUC 84,88% +/-0,35, cho tháº¥y hiá»‡u nÄƒng cáº¡nh tranh trong má»™t táº­p dá»¯ liá»‡u Ä‘a dáº¡ng hÆ¡n. [CÃ¢u káº¿t/Chuyá»ƒn Ã½]: CÃ¡c chá»‰ sá»‘ Ä‘á»‹nh lÆ°á»£ng cho tháº¥y tiá»m nÄƒng cá»§a phÆ°Æ¡ng phÃ¡p, nhÆ°ng chÃºng ta váº«n cáº§n quan sÃ¡t mÃ´ hÃ¬nh Ä‘ang chÃº Ã½ vÃ o Ä‘Ã¢u vÃ  metadata Ä‘Ã³ng gÃ³p nhÆ° tháº¿ nÃ o. Xin má»i há»™i Ä‘á»“ng Ä‘áº¿n vá»›i pháº§n phÃ¢n tÃ­ch Explainable AI.""",
    29: """[CÃ¢u tiáº¿p ná»‘i]: Niá»m tin vÃ o má»™t há»‡ thá»‘ng há»— trá»£ y khoa khÃ´ng chá»‰ Ä‘áº¿n tá»« chá»‰ sá»‘ AUC, mÃ  cÃ²n Ä‘áº¿n tá»« kháº£ nÄƒng giáº£i thÃ­ch. ChÃºng em sá»­ dá»¥ng Grad-CAM vÃ  SHAP Ä‘á»ƒ kháº£o sÃ¡t hoáº¡t Ä‘á»™ng cá»§a mÃ´ hÃ¬nh. [Ná»™i dung chÃ­nh]: BÃªn trÃ¡i lÃ  báº£n Ä‘á»“ nhiá»‡t Grad-CAM. á»ž hÃ ng trÃªn (Baseline - chá»‰ dÃ¹ng áº£nh), vÃ¹ng chÃº Ã½ cá»§a mÃ´ hÃ¬nh cÃ³ xu hÆ°á»›ng phÃ¢n tÃ¡n hÆ¡n. Trong khi Ä‘Ã³, á»Ÿ hÃ ng dÆ°á»›i, mÃ´ hÃ¬nh FiLM (Metadata Guided) cho tháº¥y vÃ¹ng kÃ­ch hoáº¡t táº­p trung hÆ¡n vÃ o khu vá»±c tá»•n thÆ°Æ¡ng trong cÃ¡c vÃ­ dá»¥ minh há»a. BÃªn pháº£i lÃ  biá»ƒu Ä‘á»“ SHAP Ä‘o lÆ°á»ng Ä‘Ã³ng gÃ³p cá»§a dá»¯ liá»‡u lÃ¢m sÃ ng. Vá»›i Strategy 2 - Concatenation, cÃ¡c giÃ¡ trá»‹ SHAP cá»§a metadata táº­p trung gáº§n má»‘c 0 hÆ¡n; cÃ²n á»Ÿ Strategy 3 - FiLM, Ä‘á»™ phÃ¢n tÃ¡n lá»›n hÆ¡n, gá»£i Ã½ ráº±ng metadata cÃ³ áº£nh hÆ°á»Ÿng rÃµ hÆ¡n Ä‘áº¿n Ä‘áº§u ra mÃ´ hÃ¬nh. Tuy nhiÃªn, cÃ¡c phÃ¢n tÃ­ch nÃ y mang Ã½ nghÄ©a há»— trá»£ diá»…n giáº£i, chÆ°a pháº£i báº±ng chá»©ng nhÃ¢n quáº£ hoáº·c xÃ¡c nháº­n lÃ¢m sÃ ng Ä‘á»™c láº­p. [CÃ¢u káº¿t/Chuyá»ƒn Ã½]: Tá»« cÃ¡c thá»±c nghiá»‡m Ä‘á»‹nh lÆ°á»£ng vÃ  phÃ¢n tÃ­ch diá»…n giáº£i trÃªn, chÃºng em xin tá»•ng káº¿t láº¡i giÃ¡ trá»‹ chÃ­nh cá»§a Ä‘á» tÃ i.""",
    31: """[CÃ¢u tiáº¿p ná»‘i]: Äá»ƒ tá»•ng káº¿t láº¡i, nghiÃªn cá»©u cá»§a chÃºng em khÃ´ng chá»‰ dá»«ng láº¡i á»Ÿ lÃ½ thuyáº¿t trÃªn máº·t giáº¥y, mÃ  cÃ²n xÃ¢y dá»±ng má»™t pipeline thá»±c nghiá»‡m cho bÃ i toÃ¡n há»c sÃ¢u Ä‘a phÆ°Æ¡ng thá»©c trong da liá»…u. [Ná»™i dung chÃ­nh]: Vá» máº·t nghiÃªn cá»©u, Ä‘á» tÃ i má»Ÿ rá»™ng Ä‘Ã¡nh giÃ¡ trÃªn cÃ¡c kiáº¿n trÃºc hiá»‡n Ä‘áº¡i nhÆ° ConvNeXt vÃ  ViT, Ä‘á»“ng thá»i Ä‘á»‘i chiáº¿u bá»‘n chiáº¿n lÆ°á»£c dung há»£p gá»“m Image-Only, Concatenation, FiLM vÃ  Gating. Káº¿t quáº£ trong bÃ i bÃ¡o cho tháº¥y FiLM cÃ³ thá»ƒ cáº£i thiá»‡n hiá»‡u nÄƒng hoáº·c Ä‘á»™ á»•n Ä‘á»‹nh á»Ÿ má»™t sá»‘ cáº¥u hÃ¬nh, ná»•i báº­t lÃ  ConvNeXt trÃªn HAM10000. Vá» máº·t minh báº¡ch, Grad-CAM vÃ  SHAP Ä‘Æ°á»£c sá»­ dá»¥ng Ä‘á»ƒ kháº£o sÃ¡t vÃ¹ng chÃº Ã½ thá»‹ giÃ¡c vÃ  vai trÃ² cá»§a metadata. ToÃ n bá»™ thiáº¿t káº¿ Ä‘Ã¡nh giÃ¡ Ä‘Æ°á»£c xÃ¢y dá»±ng theo giao thá»©c group split á»Ÿ cáº¥p Ä‘á»™ tá»•n thÆ°Æ¡ng, dá»±a trÃªn `lesion_id`, nháº±m háº¡n cháº¿ viá»‡c cÃ¹ng má»™t tá»•n thÆ°Æ¡ng xuáº¥t hiá»‡n á»Ÿ cáº£ táº­p há»c vÃ  táº­p Ä‘Ã¡nh giÃ¡. [CÃ¢u káº¿t/Chuyá»ƒn Ã½]: Máº·c dÃ¹ Ä‘áº¡t Ä‘Æ°á»£c nhá»¯ng káº¿t quáº£ Ä‘Ã¡ng ghi nháº­n, nhÃ³m nghiÃªn cá»©u váº«n nháº­n thá»©c rÃµ nhá»¯ng giá»›i háº¡n cá»§a Ä‘á» tÃ i Ä‘á»ƒ hÆ°á»›ng tá»›i tÆ°Æ¡ng lai.""",
}


def replace_paragraph(paragraph, text):
    if paragraph.runs:
        paragraph.runs[0].text = text
        for run in paragraph.runs[1:]:
            run.text = ""
    else:
        paragraph.add_run(text)


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copy2(SOURCE, OUTPUT)
    document = Document(OUTPUT)
    for index, text in REVISED_PARAGRAPHS.items():
        replace_paragraph(document.paragraphs[index], text)
    document.save(OUTPUT)
    print(OUTPUT)


if __name__ == "__main__":
    main()
